### ISSUE TITLE
navbar, community, project text edits

### ISSUE THREAD

**Issue by seichris** [abundance-stack/donationsapp#44]
## Projects

- 3 active campaigns, with the text from https://docs.google.com/document/d/15XgJ1KljfA6dwrBI-HiVZhFBBP-oGcWNva49FdAVvCg/edit
- deactivate all other except for "reward network activity", "SDG 11", "Join us"

## Community Text

Title: Sarafu Inclusive Currency
Text: With unstable food systems, deteriorating markets and supply chains, and eroding health systems, knowing how to support front-line interventions is crucial to providing relief and building more resilient communities.

The Red Cross, in partnership with Kenya-based Grassroots Economics, have developed a revolutionary solution called Community Inclusion Currencies (CICs) to address the needs of first responders and vulnerable communities during this time of peril and uncertainty.

CICs are blockchain-based digital vouchers that community members trade to buy and sell basic needs in the face of scarce national currency. Over the past decade, CICs have rapidly grown their distribution network to over 12,000 informal businesses (e.g. vegetable, maize, water sellers) in some of the most vulnerable communities of Kenya.

Together with technology provider Multiply.Charity, the Red Cross and Grassroots Economics, have created three targeted campaigns to help those most exposed to COVID19’s negative social and economic externalities.

Button: Change title to “Donate”

## Navbar

- add blue donate button

**Comment by Kisgus** [comment]
I had in mind to only have 3 active campaigns, showing 6 additional of your campaigns that are de-activated to illustrate the concept:


**Row 2:** shows personal campaigns or specific projects like a school (school has to be de-activated)

![Screen Shot 2020-03-29 at 2 22 00 PM](https://user-images.githubusercontent.com/18598519/77888406-8284d800-726c-11ea-991a-8c3d3ea7bb7f.png)

**Row 3:** shows the SDG specific goal, network contribution campaigns and join us
![Screen Shot 2020-03-29 at 2 24 08 PM](https://user-images.githubusercontent.com/18598519/77888422-89abe600-726c-11ea-83a0-07b48bd293f2.png)

**Comment by seichris** [comment]
now https://github.com/abundance-stack/donationsapp/issues/56
