### ISSUE TITLE
Finish Celo integration and launch Venezuela testnet Campaign

### ISSUE THREAD

**Issue by Kisgus** [abundance-stack/donationsapp#45]
- Deploy to Venezuela campaign
- Update description on campaign
- Record video with Moonpay integration and Celo wallet (like before)

**Comment by Kisgus** [comment]
Looks great. Some annoying updates needed :)

**xDAI mention in FAQ description**

![91846872_505650067008319_9156021284591632384_n](https://user-images.githubusercontent.com/18598519/78174150-15826580-7459-11ea-801c-9309c945eb67.jpg)


...Proposed text instead:


**Where does my donation go?**

Your donation is converted into stable cUSD cryptocurrency and securely stored on the Celo blockchain. After a seconds, your donee receives the currency tokens in the Celo blockchain wallet and is able to spend them. Meanwhile you can track your donation’s impact the impact dashboard.

**How much does a donee receive?**

All donations are converted to stable cUSD currency and send directly to the recipients. 

****xDAI stats on Venezuela page** maybe just delete all of this?

![91757016_506477110026544_7541506875745894400_n](https://user-images.githubusercontent.com/18598519/78174133-0e5b5780-7459-11ea-8383-2e51ed17c3e6.jpg)

**Comment by amiromayer** [comment]
Resolved with https://github.com/abundance-stack/donationsapp/commit/89954a6c3537ef57093ada5544b92d4cfbdffce5
